from PySide.QtGui import QApplication, QStandardItemModel, QStandardItem
from PySide.QtCore import QRect
import sys

import Marb

if __name__ == "__main__":
    
    app = QApplication(sys.argv)
    model = QStandardItemModel()
    it0 = QStandardItem( "Item0" )
    
    it1 = QStandardItem( "Item5" )
    it2 = QStandardItem( "Item7" )
    it1.appendRow( it2 )
    it2 = QStandardItem( "Item8" )
    it1.appendRow( it2 )
    it3 = QStandardItem( "Item10" )
    it2.appendRow( it3 )
    it0.appendRow( it1 )
    it1 = QStandardItem( "Item5" )
    it2 = QStandardItem( "Item7" )
    it1.appendRow( it2 )
    it2 = QStandardItem( "Item8" )
    it1.appendRow( it2 )
    it3 = QStandardItem( "Item10" )
    it2.appendRow( it3 )
    it0.appendRow( it1 )
    it1 = QStandardItem( "Item5" )
    it2 = QStandardItem( "Item7" )
    it1.appendRow( it2 )
    it2 = QStandardItem( "Item8" )
    it1.appendRow( it2 )
    it3 = QStandardItem( "Item10" )
    it2.appendRow( it3 )
    it0.appendRow( it1 )
    it1 = QStandardItem( "Item5" )
    it2 = QStandardItem( "Item7" )
    it1.appendRow( it2 )
    it2 = QStandardItem( "Item8" )
    it1.appendRow( it2 )
    it3 = QStandardItem( "Item10" )
    it2.appendRow( it3 )
    it0.appendRow( it1 )
    it1 = QStandardItem( "Item5" )
    it2 = QStandardItem( "Item7" )
    it1.appendRow( it2 )
    it2 = QStandardItem( "Item8" )
    it1.appendRow( it2 )
    it3 = QStandardItem( "Item10" )
    it2.appendRow( it3 )
    it0.appendRow( it1 )
    it1 = QStandardItem( "Item5" )
    it2 = QStandardItem( "Item7" )
    it1.appendRow( it2 )
    it2 = QStandardItem( "Item8" )
    it1.appendRow( it2 )
    it3 = QStandardItem( "Item10" )
    it2.appendRow( it3 )
    it0.appendRow( it1 )
    
    it1 = QStandardItem( "Item6" )
    it0.appendRow( it1 )
    model.appendRow( it0 )

    style = Marb.TreeStyle()
    style.setShape( Marb.Shape.Ellipse )
    style.setDisplayText(False)
    t1 = Marb.RadialTree()
#    t1.setDirectConnection(True)
    t1.setTreeStyle(style)
    t1.setItemRect( QRect( -20, -20, 40, 40 ) )
    t1.setModel(model)
    t1.resolvePositions()
    t1.show()
    t1.move( 50, 50 )
    app.exec_()